# FROM python:3.10

# WORKDIR /app
# COPY . .

# RUN pip install -r requirements.txt

# CMD ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "8000"]


FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY api/ api/
COPY src/ src/

CMD ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "8000"]
